export const productList = [
  // {
  //   id: 1,
  //   url: '/assets/products/collection/marble-1.png',
  //   name: 'Luna Chopping Board',
  //   quantity: 20,
  //   price: 850,
  //   color: ['white'],
  // },
  // {
  //   id: 2,
  //   url: '/assets/products/collection/marble-2.png',
  //   name: 'Jaya Coaster Set',
  //   quantity: 5,
  //   price: 800,
  //   color: ['white'],
  // },
  // {
  //   id: 3,
  //   url: '/assets/products/collection/marble-3.png',
  //   name: 'Lisa Kitchen Tissue Holder',
  //   quantity: 8,
  //   price: 750,
  //   color: ['white'],
  // },
  // {
  //   id: 4,
  //   url: '/assets/products/collection/marble-4.png',
  //   name: 'Pauline Bathroom Set',
  //   quantity: 10,
  //   price: 1500,
  //   color: ['white'],
  // },
  {
    id: 5,
    url: '/assets/products/collection/marble-5.png',
    name: 'Quincy Display Set',
    quantity: 5,
    price: 2500,
    color: ['white'],
  },
  {
    id: 6,
    url: '/assets/products/collection/marble-6.png',
    name: 'Marc Kichen Utensil Holder',
    quantity: 10,
    price: 650,
    color: ['white'],
  },
  {
    id: 7,
    url: '/assets/products/collection/marble-7.png',
    name: 'Grace Table Food Display',
    quantity: 5,
    price: 3200,
    color: ['white'],
  },
  {
    id: 8,
    url: '/assets/products/collection/marble-8.png',
    name: 'Brian Candle Holder Set (6pcs)',
    quantity: 10,
    price: 900,
    color: ['white'],
  },
  {
    id: 9,
    url: '/assets/products/collection/marble-9.png',
    name: 'Kianna Flower Vase',
    quantity: 5,
    price: 1400,
    color: ['white'],
  },
  {
    id: 10,
    url: '/assets/products/collection/marble-10.png',
    name: 'Luis Chopping Board Set',
    quantity: 5,
    price: 5000,
    color: ['white'],
  },
  {
    id: 11,
    url: '/assets/products/collection/marble-11.png',
    name: 'Magda Flower Vase',
    quantity: 20,
    price: 550,
    color: ['white'],
  },
  {
    id: 12,
    url: '/assets/products/collection/marble-12.png',
    name: 'Peter Candle Holder',
    quantity: 20,
    price: 350,
    color: ['white'],
  },
  {
    id: 13,
    url: '/assets/products/collection/marble-13.png',
    name: 'Sylvia Candle Holder',
    quantity: 10,
    price: 320,
    color: ['white'],
  },
  {
    id: 14,
    url: '/assets/products/collection/marble-14.png',
    name: 'Maria Book Cloud Holder',
    quantity: 10,
    price: 1100,
    color: ['white'],
  },
  {
    id: 15,
    url: '/assets/products/collection/marble-15.png',
    name: 'Jasmine Book Holder',
    quantity: 10,
    price: 1100,
    color: ['white'],
  },
  {
    id: 16,
    url: '/assets/products/collection/marble-16.png',
    name: 'Brian Chopping Board',
    quantity: 10,
    price: 850,
    color: ['white'],
  },
  {
    id: 17,
    url: '/assets/products/collection/marble-17.jpg',
    name: 'Lara Soap Holder',
    quantity: 10,
    price: 750,
    color: ['white'],
  },
  {
    id: 18,
    url: '/assets/products/collection/marble-18.png',
    name: 'Lara Phone Holder',
    quantity: 10,
    price: 750,
    color: ['white'],
  },
  {
    id: 19,
    url: '/assets/products/collection/marble-19.png',
    name: 'Kira Book Holder',
    quantity: 10,
    price: 900,
    color: ['white'],
  },
  {
    id: 20,
    url: '/assets/products/collection/marble-20.png',
    name: 'Samantha Tissue Holder',
    quantity: 10,
    price: 980,
    color: ['white'],
  },
  {
    id: 21,
    url: '/assets/products/collection/marble-21.png',
    name: 'Samantha Tissue Holder',
    quantity: 10,
    price: 980,
    color: ['white'],
  },
  {
    id: 22,
    url: '/assets/products/collection/marble-22.png',
    name: 'Paul Wine Holder',
    quantity: 5,
    price: 2800,
    color: ['white'],
  },
  {
    id: 23,
    url: '/assets/products/collection/marble-23.png',
    name: 'Clara Jewelry Rack',
    quantity: 10,
    price: 1600,
    color: ['white'],
  },
  {
    id: 24,
    url: '/assets/products/collection/marble-24.png',
    name: 'Tic Tac Toe',
    quantity: 5,
    price: 8000,
    color: ['white'],
  },
  {
    id: 25,
    url: '/assets/products/collection/marble-25.jpg',
    name: 'Tara Book Keeper',
    quantity: 5,
    price: 1200,
    color: ['white'],
  },
  {
    id: 26,
    url: '/assets/products/collection/marble-26.png',
    name: 'Karla Salt & Pepper Set',
    quantity: 10,
    price: 750,
    color: ['white'],
  },
  {
    id: 27,
    url: '/assets/products/collection/marble-27.png',
    name: 'Tina Jewelry Display Set',
    quantity: 10,
    price: 1800,
    color: ['white'],
  },
  {
    id: 28,
    url: '/assets/products/collection/marble-28.png',
    name: 'Mina Jewelry Display Set',
    quantity: 10,
    price: 3800,
    color: ['white'],
  },
  {
    id: 29,
    url: '/assets/products/collection/marble-29.png',
    name: 'Klarita Flower Rounded Vase',
    quantity: 15,
    price: 1600,
    color: ['white'],
  },
  {
    id: 30,
    url: '/assets/products/collection/marble-30.png',
    name: 'Sam Flower Vase Set',
    quantity: 5,
    price: 3500,
    color: ['white'],
  },
  {
    id: 31,
    url: '/assets/products/collection/marble-31.png',
    name: 'Vida Utensil Holder',
    quantity: 5,
    price: 400,
    color: ['white'],
  },
  {
    id: 32,
    url: '/assets/products/collection/marble-32.png',
    name: 'Vanna Utensil Holder',
    quantity: 5,
    price: 400,
    color: ['white'],
  },
  {
    id: 33,
    url: '/assets/products/collection/marble-33.png',
    name: 'Sien Family Toothbrush Holder Set',
    quantity: 5,
    price: 1900,
    color: ['white'],
  },
  {
    id: 34,
    url: '/assets/products/collection/marble-34.png',
    name: 'Lora Couple Toothbrush Holder Set',
    quantity: 5,
    price: 750,
    color: ['white'],
  },
  {
    id: 35,
    url: '/assets/products/collection/marble-35.png',
    name: 'Troy Candle Swirl Holder',
    quantity: 5,
    price: 1800,
    color: ['white'],
  },
  {
    id: 36,
    url: '/assets/products/collection/marble-36.png',
    name: 'Marius Candle Swirl Holder',
    quantity: 5,
    price: 1800,
    color: ['white'],
  },
  {
    id: 37,
    url: '/assets/products/collection/marble-37.png',
    name: 'Maxa Candle Holder',
    quantity: 5,
    price: 380,
    color: ['white'],
  },
  {
    id: 38,
    url: '/assets/products/collection/marble-38.png',
    name: 'Marian Card Holder',
    quantity: 5,
    price: 450,
    color: ['white'],
  },
  {
    id: 39,
    url: '/assets/products/collection/marble-39.png',
    name: 'Glen Card Holder',
    quantity: 5,
    price: 420,
    color: ['white'],
  },
  {
    id: 40,
    url: '/assets/products/collection/marble-40.png',
    name: 'Blee Cloudy Book Holder',
    price: 120,
    color: ['white'],
  },
  {
    id: 41,
    url: '/assets/products/collection/marble-41.png',
    name: 'Teele Tiny Mortar and Pestle',
    price: 550,
    color: ['white'],
  },
  {
    id: 42,
    url: '/assets/products/collection/marble-42.png',
    name: 'Tara Tiny Mortar and Pestle',
    price: 550,
    color: ['white'],
  },
  {
    id: 43,
    url: '/assets/products/collection/marble-43.png',
    name: 'Sara Salt and Pepper Set',
    price: 750,
    color: ['grey', 'white'],
  },
  {
    id: 44,
    url: '/assets/products/collection/marble-44.png',
    name: 'Cindy Match Holder',
    price: 350,
    color: ['white'],
  },
  {
    id: 45,
    url: '/assets/products/collection/marble-45.png',
    name: 'Sisa Glasses Holder',
    price: 950,
    color: ['white'],
  },
  {
    id: 46,
    url: '/assets/products/collection/marble-46.png',
    name: 'Manny Glasses Holder',
    price: 950,
    color: ['white'],
  },
  {
    id: 47,
    url: '/assets/products/collection/marble-47.png',
    name: 'Faja Accessory Holder',
    price: 550,
    color: ['white'],
  },
  {
    id: 48,
    url: '/assets/products/collection/marble-48.png',
    name: 'Lea Brush Holder',
    price: 1200,
    color: ['white'],
  },
  {
    id: 49,
    url: '/assets/products/collection/marble-49.png',
    name: 'Bree Phone Holder',
    price: 750,
    color: ['white'],
  },
  {
    id: 50,
    url: '/assets/products/collection/marble-50.png',
    name: 'Laila Toothpick Holder',
    price: 350,
    color: ['white'],
  },
  {
    id: 51,
    url: '/assets/products/collection/marble-51.png',
    name: 'Banny Couple Toothbrush Holder Set',
    price: 650,
    color: ['white'],
  },
  {
    id: 52,
    url: '/assets/products/collection/marble-52.png',
    name: 'Zara Ring Display Rack',
    price: 320,
    color: ['white'],
  },
  {
    id: 53,
    url: '/assets/products/collection/marble-53.png',
    name: 'Zara Ring Display Rack',
    price: 320,
    color: ['white'],
  },
];

export const newProducts = [
  {
    id: '1',
    url: '/assets/products/christmas/christmas-4.png',
  },
  {
    id: '2',
    url: '/assets/products/christmas/christmas-3.png',
  },
  {
    id: '3',
    url: '/assets/products/christmas/christmas-7.png',
  },
  {
    id: '4',
    url: '/assets/products/christmas/christmas-6.png',
  },
  {
    id: '5',
    url: '/assets/products/christmas/christmas-10.png',
  },
];

export const bestSellers = [
  {
    id: '1',
    url: '/assets/products/best-seller/best-seller-1.png',
  },
  {
    id: '2',
    url: '/assets/products/best-seller/best-seller-2.png',
  },
  {
    id: '3',
    url: '/assets/products/best-seller/best-seller-3.png',
  },
  {
    id: '4',
    url: '/assets/products/best-seller/best-seller-4.png',
  },
  {
    id: '5',
    url: '/assets/products/best-seller/best-seller-5.png',
  },
];
